spring:
  rabbitmq:
    host: localhost
    password: guest
    port: 5672
    username: guest

rabbit:
  mqproperties:
    teacher:
      queue: tech-queue
      exchange: tech-exchange
      routing: tech-routing
    student:
      queue: stud-queue
      exchange: stud-exchange
      routing: stud-routing




