spring:
  rabbitmq:
    host: localhost
    password: guest
    port: 5672
    username: guest
  datasource:
    url: jdbc:mysql://localhost:3306/rabbitMq_Learning?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: Root123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
   # properties:
   #   hibernate.dialect: org.hibernate.dialect.MySQL8Dialect # Adjust according to your MySQL version

  # Spring Security Configuration (optional)
  security:
    user:
      password: encoded_password

rabbit:
  mqproperties:
    teacher:
      queue: tech-queue
      exchange: tech-exchange
      routing: tech-routing
    student:
      queue: stud-queue
      exchange: stud-exchange
      routing: stud-routing

management:
  endpoints:
    web:
      exposure:
        include: "*"          # Expose all Actuator endpoints
  endpoint:
    health:
      show-details: always    # Show health details in the health endpoint

# JWT configuration
jwt:
 secret: your_secret_key
 expiration: 3600000  # 1 hour in milliseconds





